//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMS.LanguageResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountListItem {
            get {
                return ResourceManager.GetString("AccountListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string AddCaps {
            get {
                return ResourceManager.GetString("AddCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Guest.
        /// </summary>
        internal static string AddGuest {
            get {
                return ResourceManager.GetString("AddGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Guest Patient.
        /// </summary>
        internal static string AddingGuestPatient {
            get {
                return ResourceManager.GetString("AddingGuestPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        internal static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress:.
        /// </summary>
        internal static string AdressColon {
            get {
                return ResourceManager.GetString("AdressColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergens:.
        /// </summary>
        internal static string AllergensColon {
            get {
                return ResourceManager.GetString("AllergensColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment is canceled successfully..
        /// </summary>
        internal static string AppointmentCanceledMessage {
            get {
                return ResourceManager.GetString("AppointmentCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date:.
        /// </summary>
        internal static string AppointmentDateColon {
            get {
                return ResourceManager.GetString("AppointmentDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string AppointmentsListItem {
            get {
                return ResourceManager.GetString("AppointmentsListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Update.
        /// </summary>
        internal static string AppointmentUpdate {
            get {
                return ResourceManager.GetString("AppointmentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date:.
        /// </summary>
        internal static string BirthDateColon {
            get {
                return ResourceManager.GetString("BirthDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type:.
        /// </summary>
        internal static string BloodTypeColon {
            get {
                return ResourceManager.GetString("BloodTypeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Appointment.
        /// </summary>
        internal static string CancelAppointment {
            get {
                return ResourceManager.GetString("CancelAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string CancelCaps {
            get {
                return ResourceManager.GetString("CancelCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Appointment:.
        /// </summary>
        internal static string ChooseAppointmentColon {
            get {
                return ResourceManager.GetString("ChooseAppointmentColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose appointment to cancel..
        /// </summary>
        internal static string ChooseAppointmentToCancelMessage {
            get {
                return ResourceManager.GetString("ChooseAppointmentToCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose appointment to update..
        /// </summary>
        internal static string ChooseAppointmentToUpdateMessage {
            get {
                return ResourceManager.GetString("ChooseAppointmentToUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose patient to delete..
        /// </summary>
        internal static string ChoosePatientToDeleteMessage {
            get {
                return ResourceManager.GetString("ChoosePatientToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose patient to unblock..
        /// </summary>
        internal static string ChoosePatientToUnblockMessage {
            get {
                return ResourceManager.GetString("ChoosePatientToUnblockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose patient to update..
        /// </summary>
        internal static string ChoosePatientToUpdateMessage {
            get {
                return ResourceManager.GetString("ChoosePatientToUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic Pains:.
        /// </summary>
        internal static string ChronicPainsColon {
            get {
                return ResourceManager.GetString("ChronicPainsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string CityColon {
            get {
                return ResourceManager.GetString("CityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string CountryColon {
            get {
                return ResourceManager.GetString("CountryColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string DateColon {
            get {
                return ResourceManager.GetString("DateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor:.
        /// </summary>
        internal static string DoctorColon {
            get {
                return ResourceManager.GetString("DoctorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is on vacation at the specified time..
        /// </summary>
        internal static string DoctorOnVacationMessage {
            get {
                return ResourceManager.GetString("DoctorOnVacationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string DoctorsListItem {
            get {
                return ResourceManager.GetString("DoctorsListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is unavailable at the specified time..
        /// </summary>
        internal static string DoctorUnavailableMessage {
            get {
                return ResourceManager.GetString("DoctorUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string DurationColon {
            get {
                return ResourceManager.GetString("DurationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string EmailColon {
            get {
                return ResourceManager.GetString("EmailColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time:.
        /// </summary>
        internal static string EndTimeColon {
            get {
                return ResourceManager.GetString("EndTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Date:.
        /// </summary>
        internal static string ExaminationDateColon {
            get {
                return ResourceManager.GetString("ExaminationDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Scheduling.
        /// </summary>
        internal static string ExaminationScheduling {
            get {
                return ResourceManager.GetString("ExaminationScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields..
        /// </summary>
        internal static string FillFieldsMessage {
            get {
                return ResourceManager.GetString("FillFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        internal static string FullNameColon {
            get {
                return ResourceManager.GetString("FullNameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATE.
        /// </summary>
        internal static string GenerateCaps {
            get {
                return ResourceManager.GetString("GenerateCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest:.
        /// </summary>
        internal static string GuestColon {
            get {
                return ResourceManager.GetString("GuestColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string HomePageListItem {
            get {
                return ResourceManager.GetString("HomePageListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date format. (dd.MM.yyyy.).
        /// </summary>
        internal static string IncorrectDateFormatMessage {
            get {
                return ResourceManager.GetString("IncorrectDateFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email address format..
        /// </summary>
        internal static string IncorrectEmailFormatMessage {
            get {
                return ResourceManager.GetString("IncorrectEmailFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect phone number format..
        /// </summary>
        internal static string IncorrectPhoneNumberFormatMessage {
            get {
                return ResourceManager.GetString("IncorrectPhoneNumberFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater then start date..
        /// </summary>
        internal static string InvalidDatesMessage {
            get {
                return ResourceManager.GetString("InvalidDatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmbg.
        /// </summary>
        internal static string Jmbg {
            get {
                return ResourceManager.GetString("Jmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmbg:.
        /// </summary>
        internal static string JmbgColon {
            get {
                return ResourceManager.GetString("JmbgColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jmbg must have exactly 13 digits..
        /// </summary>
        internal static string JmbgNumberMessage {
            get {
                return ResourceManager.GetString("JmbgNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string LastNameColon {
            get {
                return ResourceManager.GetString("LastNameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lbo.
        /// </summary>
        internal static string Lbo {
            get {
                return ResourceManager.GetString("Lbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lbo:.
        /// </summary>
        internal static string LboColon {
            get {
                return ResourceManager.GetString("LboColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lbo must consist of digits..
        /// </summary>
        internal static string LboNumberMessage {
            get {
                return ResourceManager.GetString("LboNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameColon {
            get {
                return ResourceManager.GetString("NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vacation Adding.
        /// </summary>
        internal static string NewVacationAdding {
            get {
                return ResourceManager.GetString("NewVacationAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can input your notification here..
        /// </summary>
        internal static string NotificationDefaultText {
            get {
                return ResourceManager.GetString("NotificationDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordColon {
            get {
                return ResourceManager.GetString("PasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Adding.
        /// </summary>
        internal static string PatientAdding {
            get {
                return ResourceManager.GetString("PatientAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient:.
        /// </summary>
        internal static string PatientColon {
            get {
                return ResourceManager.GetString("PatientColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is deleted successfully..
        /// </summary>
        internal static string PatientDeletedMessage {
            get {
                return ResourceManager.GetString("PatientDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is not banned..
        /// </summary>
        internal static string PatientNotBannedMessage {
            get {
                return ResourceManager.GetString("PatientNotBannedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string PatientsListItem {
            get {
                return ResourceManager.GetString("PatientsListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is unblocked successfully..
        /// </summary>
        internal static string PatientUnblockedMessage {
            get {
                return ResourceManager.GetString("PatientUnblockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Update.
        /// </summary>
        internal static string PatientUpdate {
            get {
                return ResourceManager.GetString("PatientUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient does not have account..
        /// </summary>
        internal static string PatientWithoutAccountMessage {
            get {
                return ResourceManager.GetString("PatientWithoutAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        internal static string PhoneNumberColon {
            get {
                return ResourceManager.GetString("PhoneNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code:.
        /// </summary>
        internal static string PostalCodeColon {
            get {
                return ResourceManager.GetString("PostalCodeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT.
        /// </summary>
        internal static string QuitCaps {
            get {
                return ResourceManager.GetString("QuitCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ReportListItem {
            get {
                return ResourceManager.GetString("ReportListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room:.
        /// </summary>
        internal static string RoomColon {
            get {
                return ResourceManager.GetString("RoomColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room is not occupied during the specified period..
        /// </summary>
        internal static string RoomNotOccupied {
            get {
                return ResourceManager.GetString("RoomNotOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number: .
        /// </summary>
        internal static string RoomNumberColon {
            get {
                return ResourceManager.GetString("RoomNumberColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Occupancy Report.
        /// </summary>
        internal static string RoomOccupancyReport {
            get {
                return ResourceManager.GetString("RoomOccupancyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room is unavailable at the specified time..
        /// </summary>
        internal static string RoomUnavailableMessage {
            get {
                return ResourceManager.GetString("RoomUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULE.
        /// </summary>
        internal static string ScheduleCaps {
            get {
                return ResourceManager.GetString("ScheduleCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Examination.
        /// </summary>
        internal static string ScheduleExamination {
            get {
                return ResourceManager.GetString("ScheduleExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Surgery.
        /// </summary>
        internal static string ScheduleSurgery {
            get {
                return ResourceManager.GetString("ScheduleSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary: .
        /// </summary>
        internal static string SecretaryColon {
            get {
                return ResourceManager.GetString("SecretaryColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary&apos;s Account.
        /// </summary>
        internal static string SecretarysAccount {
            get {
                return ResourceManager.GetString("SecretarysAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one role..
        /// </summary>
        internal static string SelectRoleMessage {
            get {
                return ResourceManager.GetString("SelectRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex:.
        /// </summary>
        internal static string SexColon {
            get {
                return ResourceManager.GetString("SexColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization:.
        /// </summary>
        internal static string SpecializationColon {
            get {
                return ResourceManager.GetString("SpecializationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        internal static string StartTimeColon {
            get {
                return ResourceManager.GetString("StartTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery Date:.
        /// </summary>
        internal static string SurgeryDateColon {
            get {
                return ResourceManager.GetString("SurgeryDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery Scheduling.
        /// </summary>
        internal static string SurgeryScheduling {
            get {
                return ResourceManager.GetString("SurgeryScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        internal static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Appointment.
        /// </summary>
        internal static string UpdateAppointment {
            get {
                return ResourceManager.GetString("UpdateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        internal static string UpdateCaps {
            get {
                return ResourceManager.GetString("UpdateCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Examination.
        /// </summary>
        internal static string UrgentExamination {
            get {
                return ResourceManager.GetString("UrgentExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent examination is scheduled successfully..
        /// </summary>
        internal static string UrgentExaminationScheduledMessage {
            get {
                return ResourceManager.GetString("UrgentExaminationScheduledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Examination Scheduling.
        /// </summary>
        internal static string UrgentExaminationScheduling {
            get {
                return ResourceManager.GetString("UrgentExaminationScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Surgery.
        /// </summary>
        internal static string UrgentSurgery {
            get {
                return ResourceManager.GetString("UrgentSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent surgery is scheduled successfully..
        /// </summary>
        internal static string UrgentSurgeryScheduledMessage {
            get {
                return ResourceManager.GetString("UrgentSurgeryScheduledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Surgery Scheduling.
        /// </summary>
        internal static string UrgentSurgeryScheduling {
            get {
                return ResourceManager.GetString("UrgentSurgeryScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string UsernameColon {
            get {
                return ResourceManager.GetString("UsernameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation for doctor is created successfully..
        /// </summary>
        internal static string VacationCreatedMessage {
            get {
                return ResourceManager.GetString("VacationCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Days:.
        /// </summary>
        internal static string VacationDaysColon {
            get {
                return ResourceManager.GetString("VacationDaysColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of vacation days is updated successfully..
        /// </summary>
        internal static string VacationDaysUpdatedMessage {
            get {
                return ResourceManager.GetString("VacationDaysUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation End:.
        /// </summary>
        internal static string VacationEndColon {
            get {
                return ResourceManager.GetString("VacationEndColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of vacation days is not number..
        /// </summary>
        internal static string VacationNotNumberMessage {
            get {
                return ResourceManager.GetString("VacationNotNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation Start:.
        /// </summary>
        internal static string VacationStartColon {
            get {
                return ResourceManager.GetString("VacationStartColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeHomePage {
            get {
                return ResourceManager.GetString("WelcomeHomePage", resourceCulture);
            }
        }
    }
}
